// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	llm "ai-harness/llm"

	mock "github.com/stretchr/testify/mock"
)

// Client is an autogenerated mock type for the Client type
type Client struct {
	mock.Mock
}

type Client_Expecter struct {
	mock *mock.Mock
}

func (_m *Client) EXPECT() *Client_Expecter {
	return &Client_Expecter{mock: &_m.Mock}
}

// Chat provides a mock function with given fields: messages, tools
func (_m *Client) Chat(messages []llm.Message, tools []llm.ToolDefinition) (*llm.ChatResponse, error) {
	ret := _m.Called(messages, tools)

	if len(ret) == 0 {
		panic("no return value specified for Chat")
	}

	var r0 *llm.ChatResponse
	var r1 error
	if rf, ok := ret.Get(0).(func([]llm.Message, []llm.ToolDefinition) (*llm.ChatResponse, error)); ok {
		return rf(messages, tools)
	}
	if rf, ok := ret.Get(0).(func([]llm.Message, []llm.ToolDefinition) *llm.ChatResponse); ok {
		r0 = rf(messages, tools)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*llm.ChatResponse)
		}
	}

	if rf, ok := ret.Get(1).(func([]llm.Message, []llm.ToolDefinition) error); ok {
		r1 = rf(messages, tools)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Client_Chat_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Chat'
type Client_Chat_Call struct {
	*mock.Call
}

// Chat is a helper method to define mock.On call
//   - messages []llm.Message
//   - tools []llm.ToolDefinition
func (_e *Client_Expecter) Chat(messages interface{}, tools interface{}) *Client_Chat_Call {
	return &Client_Chat_Call{Call: _e.mock.On("Chat", messages, tools)}
}

func (_c *Client_Chat_Call) Run(run func(messages []llm.Message, tools []llm.ToolDefinition)) *Client_Chat_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].([]llm.Message), args[1].([]llm.ToolDefinition))
	})
	return _c
}

func (_c *Client_Chat_Call) Return(_a0 *llm.ChatResponse, _a1 error) *Client_Chat_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Client_Chat_Call) RunAndReturn(run func([]llm.Message, []llm.ToolDefinition) (*llm.ChatResponse, error)) *Client_Chat_Call {
	_c.Call.Return(run)
	return _c
}

// NewClient creates a new instance of Client. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *Client {
	mock := &Client{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
